baseURL: https://marilten.netlify.app/
languageCode: en-us
title: まりる展
theme: "PaperMod"
defaultContentLanguage: ja
enableGitInfo: true
ShowShareButtons: false     # True にすれば表示する

params:
    homeInfoParams:
        Title: もろもろをメモする
        Content: Tidying up makes you feel good.

    socialIcons: # optional
        - name: "twitter"
          url: "https://twitter.com/polo__rome"
        
